image: Visual Studio 2017

build_script:
  - msbuild "PralineServer.sln" /verbosity:minimal /p:Configuration=Debug /p:Platform="Any CPU"
  - if "%APPVEYOR_REPO_TAG%"=="true" (msbuild "PralineServer.sln" /verbosity:minimal /p:Configuration=Release /p:Platform="Any CPU")
  - if "%APPVEYOR_REPO_TAG%"=="true" (msbuild "PralineServer.sln" /verbosity:minimal /p:Configuration=ReleaseDebug /p:Platform="Any CPU")

after_build:
  - if "%APPVEYOR_REPO_TAG%"=="true" (.\deploy.cmd PralineServer)
  - if "%APPVEYOR_REPO_TAG%"=="true" (.\deploy.cmd PralineNetworkSDK)

artifacts:
  - path: Deployment/PralineNetworkSDK.zip
    name: PralineNetworkSDK
  - path: Deployment/PralineServer.zip
    name: PralineServer

deploy:
  - provider: GitHub
    auth_token:
      secure: dXgty1lPk4rS5pmgesMKZv21vfkjLjnHIwzPULPPaqJTGNqpqiDAasrN5OC8P3SH
    artifact: Deployment/*.zip
    force_update: true
    on:
      appveyor_repo_tag: true
